name: Auto Devops

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OCaml and Dune
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.12
        
    - name: Build
      run: |
        eval $(opam env)
        opam install --deps-only -y .
        opam install dune -y
        opam install ounit2 -y
        dune build

    - name: Run Tests
      run: eval $(opam env) && dune exec ./test.exe

    - name: Clean Up
      run: eval $(opam env) && dune clean
