name: OCaml CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OCaml and Dune
      run: |
        sudo apt-get update -y
        sudo apt-get install -y opam
        opam init --auto-setup --disable-sandboxing
        eval $(opam env)
        opam switch create . ocaml-base-compiler.4.12.1
        eval $(opam env)
        opam install --deps-only -y .
        opam install dune -y

    - name: Build
      run: eval $(opam env) && dune build

    - name: Run Tests
      run: eval $(opam env) && dune exec ./test.exe

    - name: Clean Up
      run: eval $(opam env) && dune clean
